version: '3.8'

services:
  db:
    container_name: redis
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: cmd/Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  webapp:
    container_name: webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_WEBAPP_URL=http://webapp:3001
      - REACT_APP_BASE_URL=http://api:8080/api
      - REACT_APP_BASE_WS_URL=ws://api:8080/api
    depends_on:
      - api